version: '3'
services:

  mysql_spider:
    build: ./docker
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: spider
      MYSQL_USER: spider
      MYSQL_PASSWORD: spider
    volumes:
      - ./scripts/spider:/docker-entrypoint-initdb.d

  mysql_backend1:
    image: mysql:5.5
    ports:
      - "3308:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: spider
      MYSQL_USER: spider
      MYSQL_PASSWORD: spider
    volumes:
      - ./scripts/mysql:/docker-entrypoint-initdb.d

  mysql_backend2:
    image: mysql:5.5
    ports:
      - "3309:3306"
    environment:
        MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        MYSQL_DATABASE: spider
        MYSQL_USER: spider
        MYSQL_PASSWORD: spider
    volumes:
      - ./scripts/mysql:/docker-entrypoint-initdb.d
